import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const packages = [
  [
    "packages/protocol",
    "Provider-neutral protocol schemas",
    "Import schemas and types from the package root; validate untrusted provider output before it crosses a trust boundary.",
    "No credentials or network calls are included.",
  ],
  [
    "packages/core",
    "Bounded decision runtime primitives",
    "Create a bounded pack and call the runtime with trusted identity, validated state, candidates, and a deadline.",
    "This package returns advisory typed data and receipts; it never authorizes or executes an action.",
  ],
  [
    "packages/evals",
    "Offline evaluation and replay helpers",
    "Import evaluators from the package root and run them against retained, redacted fixtures.",
    "Evaluation is offline by default and does not call a provider.",
  ],
  [
    "packs",
    "Built-in bounded decision packs",
    "Import `builtinPacks` from the package root and select a pack by its declared identifier.",
    "Packs are advisory and require a trusted host projection before use.",
  ],
  [
    "packages/mcp",
    "Advisory MCP server",
    "Import `createMcpServer` or `createHttpHandler` from the package root and inject a bounded runtime.",
    "The server exposes read-only advisory tools; do not expose it as an authorization or execution endpoint.",
  ],
  [
    "packages/cli",
    "Jev Fabric command-line interface",
    "Install the package and run `jev-fabric --help`; see the repository CLI reference for bounded offline commands.",
    "Live provider use requires the CLI `--live` gate, an allowlisted provider, credentials, and declared budgets. The exposed conversation key is never a valid configuration source.",
  ],
  [
    "packages/provider-openai-compatible",
    "OpenAI-compatible advisory provider adapter",
    "Import the adapter from the package root and configure an allowlisted HTTPS endpoint through the bounded runtime.",
    "Provider responses remain advisory data; endpoint and credential policy stays with the host.",
  ],
  [
    "packages/provider-typesafe",
    "TypeSafe AI and fixed Vercel AI Gateway advisory provider adapter",
    "Import `createNativeJevProvider` for the direct route or `createVercelGatewayJevProvider` for the fixed TypeSafe-compatible Gateway route, and pass credentials only through your host secret manager.",
    "Live calls require the runtime/CLI explicit `--live` controls; never commit or log API keys.",
  ],
  [
    "packages/adapters",
    "Host adapter and integration generators",
    "Import canonical adapter models and generation/validation helpers from the package root.",
    "Generated host integrations preserve advisory-only semantics and do not grant execution authority.",
  ],
] as const;

function content(
  name: string,
  description: string,
  usage: string,
  caveat: string,
): string {
  return `# ${name}\n\n${description} for [Jev Fabric](https://github.com/MokiMeow/jev-fabric).\n\n## Install\n\n\`npm install ${name}\`\n\n## Use\n\n${usage}\n\n${caveat}\n\nRead the [repository documentation](https://github.com/MokiMeow/jev-fabric/tree/main/docs), [security boundary](https://github.com/MokiMeow/jev-fabric/tree/main/docs/security), and [Apache-2.0 license](https://github.com/MokiMeow/jev-fabric/blob/main/LICENSE). Requires Node.js >=22.14 and <25.\n`;
}

export async function generatePackageReadmes({
  root = process.cwd(),
  check = false,
}: {
  root?: string;
  check?: boolean;
} = {}): Promise<void> {
  for (const [directory, description, usage, caveat] of packages) {
    const manifest = JSON.parse(
      await readFile(resolve(root, directory, "package.json"), "utf8"),
    ) as { name: string };
    const expected = content(manifest.name, description, usage, caveat);
    const path = resolve(root, directory, "README.md");
    if (check) {
      const actual = await readFile(path, "utf8").catch(() => "");
      if (actual !== expected)
        throw new Error(
          `${directory}/README.md must be generated by package-readmes`,
        );
    } else await writeFile(path, expected, "utf8");
  }
}

if (process.argv[1]?.endsWith("generate-package-readmes.mts"))
  await generatePackageReadmes({
    check: process.argv.slice(2).includes("--check"),
  });
